/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5148.teamd.gui;

import fit5148.teamd.dao.BookingDAO;
import fit5148.teamd.dao.CustomerDAO;
import fit5148.teamd.pojo.BookingFramePOJO;
import fit5148.teamd.pojo.CustomerFramePOJO;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinh Phan
 */
public class BookingFrame extends javax.swing.JFrame {

    private BookingDAO bookingDao = null;
    private CustomerDAO customerDao = null;
    private BookingFramePOJO bookingFramePojo = null;
    private CustomerFramePOJO custFramePojo = null;
    private DateFormat formatter = null;
    /**
     * Creates new form BookingFrame
     */
    public BookingFrame() {
        initComponents();
        startUpComponents();
    }

    private void startUpComponents(){
        //  Navigate from MainFrame -> SearchFrame -> BookingFrame
        initJFrame(jfBookingFrame, false, false);
        initJFrame(jfBookingSearchFrame, false, false);
        initJFrame(jfSearchResult, true, true);
        
        this.bookingDao = new BookingDAO();
        this.bookingFramePojo = new BookingFramePOJO();
        this.custFramePojo = new CustomerFramePOJO();
        this.customerDao = new CustomerDAO();
        this.formatter = new SimpleDateFormat("dd/MM/yyyy");
        
    }
    
    private void initJFrame(JFrame jf, Boolean enable, Boolean visible){
        jf.pack();
        jf.setLocationRelativeTo(null);
        jf.setVisible(visible);
        jf.setEnabled(enable);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfSearchResult = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jbtnCancelSearch = new javax.swing.JButton();
        jbtnOkay = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jtResult = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtfKeyWord = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jfBookingSearchFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jcbByDate = new javax.swing.JCheckBox();
        jcbAvailable1 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtfFrom = new javax.swing.JTextField();
        jtfTo = new javax.swing.JTextField();
        jcbRoomType = new javax.swing.JCheckBox();
        jcomRoomType = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jcbOccupancy = new javax.swing.JCheckBox();
        jcomCapacity = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jcbPrice = new javax.swing.JCheckBox();
        jcomPriceOperator = new javax.swing.JComboBox<>();
        Price1 = new javax.swing.JLabel();
        jcomPrice = new javax.swing.JComboBox<>();
        jbtnCancel = new javax.swing.JButton();
        jbtnSearchApply = new javax.swing.JButton();
        jlMessage = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane_MainFrame = new javax.swing.JScrollPane();
        jtSearch_MainFrame = new javax.swing.JTable();
        jfBookingFrame = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnMainApply = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jtfCustomerId = new javax.swing.JTextField();
        jtfFirstName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jtfLastName = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jlModeMessage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfBookId = new javax.swing.JTextField();
        jtfCheckIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCheckOut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfContactPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfContactEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfHotel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfBookDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfTotalAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfRoomId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfRoomNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfGuest1 = new javax.swing.JTextField();
        jtfGuest2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfGuest3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfGuest4 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jtfGuest5 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jtfRoomType = new javax.swing.JTextField();
        jtfPayStatus = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jlMainMessage = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jbtnBookRoom = new javax.swing.JButton();
        jbtnCreate3 = new javax.swing.JButton();
        jbtnCreate5 = new javax.swing.JButton();
        jbtnCreate4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jfSearchResult.setTitle("Search Result");
        jfSearchResult.setResizable(false);
        jfSearchResult.setSize(new java.awt.Dimension(458, 400));
        jfSearchResult.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jfSearchResultWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jfSearchResultWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jfSearchResultWindowClosing(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 40));

        jbtnCancelSearch.setText("Cancel");
        jbtnCancelSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelSearchActionPerformed(evt);
            }
        });

        jbtnOkay.setText("Okay");
        jbtnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jbtnCancelSearch))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOkay)
                    .addComponent(jbtnCancelSearch))
                .addContainerGap())
        );

        jtResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtResultKeyPressed(evt);
            }
        });
        jScrollPane.setViewportView(jtResult);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Search by Name");

        jtfKeyWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfKeyWordKeyPressed(evt);
            }
        });

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jtfKeyWord)
                .addGap(18, 18, 18)
                .addComponent(jbtnSearch)
                .addGap(8, 8, 8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addContainerGap())
        );

        javax.swing.GroupLayout jfSearchResultLayout = new javax.swing.GroupLayout(jfSearchResult.getContentPane());
        jfSearchResult.getContentPane().setLayout(jfSearchResultLayout);
        jfSearchResultLayout.setHorizontalGroup(
            jfSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchResultLayout.createSequentialGroup()
                .addGroup(jfSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jfSearchResultLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jfSearchResultLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jfSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfSearchResultLayout.setVerticalGroup(
            jfSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSearchResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jfBookingSearchFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jfBookingSearchFrame.setTitle("Booking Frame");
        jfBookingSearchFrame.setResizable(false);
        jfBookingSearchFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jfBookingSearchFrameformWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jfBookingSearchFrameformWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("UNIT:  ADMIN1");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("BOOKING  FRAME");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Search Criteria");

        jcbByDate.setText("Filter by Date");
        jcbByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbByDateActionPerformed(evt);
            }
        });

        jcbAvailable1.setText("Available Room at the moment");
        jcbAvailable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAvailable1ActionPerformed(evt);
            }
        });

        jLabel24.setText("From");

        jLabel25.setText("To");

        jtfFrom.setEnabled(false);

        jtfTo.setEnabled(false);

        jcbRoomType.setText("Room Type");
        jcbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoomTypeActionPerformed(evt);
            }
        });

        jcomRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE ROOM", "DOUBLE ROOM", "EXECUTIVE", "LUXARY" }));
        jcomRoomType.setEnabled(false);
        jcomRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomRoomTypeActionPerformed(evt);
            }
        });

        jLabel26.setText("Room Type");

        jcbOccupancy.setText("By Occupancy");
        jcbOccupancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOccupancyActionPerformed(evt);
            }
        });

        jcomCapacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4" }));
        jcomCapacity.setEnabled(false);
        jcomCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomCapacityActionPerformed(evt);
            }
        });

        jLabel27.setText("Capacity");

        jcbPrice.setText("By Price");
        jcbPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPriceActionPerformed(evt);
            }
        });

        jcomPriceOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Less than", "Greater than", "Equal" }));
        jcomPriceOperator.setEnabled(false);
        jcomPriceOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomPriceOperatorActionPerformed(evt);
            }
        });

        Price1.setText("Price");

        jcomPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "100", "150", "200", "250" }));
        jcomPrice.setEnabled(false);
        jcomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomPriceActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnSearchApply.setText("Apply");
        jbtnSearchApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchApplyActionPerformed(evt);
            }
        });

        jlMessage.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jlMessage.setForeground(new java.awt.Color(255, 0, 0));
        jlMessage.setText("                                                      ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbByDate)
                            .addComponent(jcbRoomType))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(40, 40, 40)
                                    .addComponent(jtfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcomRoomType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSearchApply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jcbPrice)
                                .addGap(108, 108, 108)
                                .addComponent(jcomPriceOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbAvailable1)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jcbOccupancy)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Price1)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcomCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jcomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(2, 2, 2))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbAvailable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbByDate)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jtfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRoomType)
                    .addComponent(jcomRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbOccupancy)
                    .addComponent(jcomCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomPriceOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price1)
                    .addComponent(jcbPrice)
                    .addComponent(jcomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnSearchApply)
                    .addComponent(jlMessage))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setLayout(new java.awt.CardLayout());

        jtSearch_MainFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtSearch_MainFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSearch_MainFrameKeyPressed(evt);
            }
        });
        jScrollPane_MainFrame.setViewportView(jtSearch_MainFrame);

        jPanel8.add(jScrollPane_MainFrame, "card2");

        javax.swing.GroupLayout jfBookingSearchFrameLayout = new javax.swing.GroupLayout(jfBookingSearchFrame.getContentPane());
        jfBookingSearchFrame.getContentPane().setLayout(jfBookingSearchFrameLayout);
        jfBookingSearchFrameLayout.setHorizontalGroup(
            jfBookingSearchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfBookingSearchFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jfBookingSearchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jfBookingSearchFrameLayout.setVerticalGroup(
            jfBookingSearchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfBookingSearchFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        jfBookingFrame.setPreferredSize(new java.awt.Dimension(900, 450));
        jfBookingFrame.setSize(new java.awt.Dimension(700, 300));

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("UNIT:  ADMIN1");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("BOOKING  FRAME");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jbtnMainApply.setText("Apply");
        jbtnMainApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMainApplyActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(255, 102, 102));
        jLabel31.setText("Customer Id");

        jtfCustomerId.setEnabled(false);

        jtfFirstName.setEnabled(false);

        jLabel30.setText("First Name");

        jtfLastName.setEnabled(false);

        jLabel35.setText("Last name");

        jLabel33.setText("Phone");

        jtfPhone.setEnabled(false);

        jtfEmail.setEnabled(false);

        jLabel34.setText("Email");

        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 204));
        jLabel36.setText("Customer Info");

        jlModeMessage.setBackground(new java.awt.Color(255, 204, 51));
        jlModeMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlModeMessage.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jlModeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jtfCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jlModeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 204));
        jLabel32.setText("Booking Info");

        jLabel1.setText("Book_Id");

        jtfBookId.setEnabled(false);

        jtfCheckIn.setEnabled(false);

        jLabel2.setText("Check_In");

        jtfCheckOut.setEnabled(false);

        jLabel3.setText("Check_Out");

        jtfContactPhone.setEnabled(false);

        jLabel4.setText("Phone");

        jtfContactEmail.setEnabled(false);

        jLabel5.setText("Email");

        jtfHotel.setEnabled(false);

        jLabel6.setText("HotelId");

        jtfBookDate.setToolTipText("");
        jtfBookDate.setEnabled(false);

        jLabel7.setText("Book_Date");

        jLabel8.setText("Total Amount");

        jtfTotalAmount.setEnabled(false);

        jLabel9.setText("Room_Id (*)");

        jtfRoomId.setEnabled(false);

        jLabel10.setText("Room Number");

        jtfRoomNumber.setEnabled(false);

        jLabel11.setText("Guest 1");

        jtfGuest1.setEnabled(false);

        jtfGuest2.setEnabled(false);

        jLabel12.setText("Guest 2");

        jtfGuest3.setEnabled(false);

        jLabel13.setText("Guest 3");

        jtfGuest4.setEnabled(false);

        jLabel37.setText("Guest 4");

        jtfGuest5.setEnabled(false);

        jLabel38.setText("Guest 5");

        jLabel39.setText("Room Type");

        jtfRoomType.setEnabled(false);

        jtfPayStatus.setEnabled(false);

        jLabel18.setText("Pay Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtfBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jtfHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfCheckIn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCheckOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfGuest2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfGuest1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfGuest3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfContactPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfContactEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBookDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfRoomType, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jtfPayStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfGuest5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfGuest4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jtfGuest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jtfGuest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jtfTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtfCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jtfGuest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jtfRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtfCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(jtfGuest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jtfRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtfContactPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(jtfGuest5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(jtfRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtfContactEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jtfPayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfBookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))))
        );

        jlMainMessage.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jlMainMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlMainMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnMainApply, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMainApply)
                    .addComponent(jButton1)
                    .addComponent(jlMainMessage))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnBookRoom.setBackground(new java.awt.Color(255, 102, 102));
        jbtnBookRoom.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jbtnBookRoom.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBookRoom.setText("Book a Room");
        jbtnBookRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnBookRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBookRoomActionPerformed(evt);
            }
        });

        jbtnCreate3.setBackground(new java.awt.Color(255, 102, 102));
        jbtnCreate3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jbtnCreate3.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCreate3.setText("Cancel Booking");
        jbtnCreate3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreate3ActionPerformed(evt);
            }
        });

        jbtnCreate5.setBackground(new java.awt.Color(255, 102, 102));
        jbtnCreate5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jbtnCreate5.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCreate5.setText("Update Booking");
        jbtnCreate5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnCreate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreate5ActionPerformed(evt);
            }
        });

        jbtnCreate4.setBackground(new java.awt.Color(255, 102, 102));
        jbtnCreate4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jbtnCreate4.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCreate4.setText("View Booking");
        jbtnCreate4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnCreate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreate4ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBookRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCreate3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jbtnCreate4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCreate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnBookRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCreate3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCreate5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCreate4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jfBookingFrameLayout = new javax.swing.GroupLayout(jfBookingFrame.getContentPane());
        jfBookingFrame.getContentPane().setLayout(jfBookingFrameLayout);
        jfBookingFrameLayout.setHorizontalGroup(
            jfBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfBookingFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jfBookingFrameLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jfBookingFrameLayout.setVerticalGroup(
            jfBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfBookingFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jfBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jfBookingFrameLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtResultKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtResultKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            //  Get the object
           doSearchCustomer();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            returnBookingFrame();
        }
        
    }//GEN-LAST:event_jtResultKeyPressed
    
    private void returnMainFrame(){
        this.jfBookingSearchFrame.removeAll();
        this.jfBookingSearchFrame.dispose();
        
        this.jfSearchResult.removeAll();
        this.jfSearchResult.dispose();
        
        this.jfBookingFrame.removeAll();
        this.jfBookingFrame.dispose();
    }
    
    private void returnBookingFrame(){
        initJFrame(jfBookingSearchFrame, false, false);
        initJFrame(jfSearchResult, false, false);
        initJFrame(jfBookingFrame, true, true);
    }
    
    private void jbtnCancelSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelSearchActionPerformed
        System.out.println("Closing Search Result");
        returnMainFrame();
    }//GEN-LAST:event_jbtnCancelSearchActionPerformed

    private void doSearchCustomer(){
        custFramePojo = customerDao.getSearchResult().get(jtResult.getSelectedRow());
        showUpPersonData(custFramePojo); // Show up the personal data to the booking frame
        returnBookingFrame();
    }
    private void jbtnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkayActionPerformed
        doSearchCustomer();
    }//GEN-LAST:event_jbtnOkayActionPerformed

    private void jfSearchResultWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jfSearchResultWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jfSearchResultWindowActivated

    private void jtfKeyWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfKeyWordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            queryCustomer2JTable();
        }
    }//GEN-LAST:event_jtfKeyWordKeyPressed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:
        queryCustomer2JTable();
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jfSearchResultWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jfSearchResultWindowClosing
        System.out.println("Closing Search Result");
        returnMainFrame();
    }//GEN-LAST:event_jfSearchResultWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void jfSearchResultWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jfSearchResultWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfSearchResultWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.println("Closing Booking Frame");
        returnMainFrame();
    }//GEN-LAST:event_formWindowClosing

   
    
    private void jcbByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbByDateActionPerformed
        // TODO add your handling code here:
        if(jcbByDate.isSelected()){
            jtfFrom.setEnabled(true);
            jtfTo.setEnabled(true);
            
        }else{
            jtfFrom.setEnabled(false);
            jtfTo.setEnabled(false);
        }
    }//GEN-LAST:event_jcbByDateActionPerformed

    private void showSearchResult(DefaultTableModel srt){
        jlMessage.setText("Found: "+srt.getRowCount()+" records");

        //  Init JFrame
        jtSearch_MainFrame.setModel(srt);
        jScrollPane_MainFrame.setViewportView(jtSearch_MainFrame);
        jtSearch_MainFrame.requestFocus();
    }
     
    private void jcbAvailable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAvailable1ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel srt = bookingDao.search("filterAvailable");
            showSearchResult(srt);
        } catch (Exception ex) {
            jlMessage.setText("No Available Room");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jcbAvailable1ActionPerformed

    private void jcbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoomTypeActionPerformed
        // TODO add your handling code here:
        if(jcbRoomType.isSelected()){
            jcomRoomType.setEnabled(true);
            
        }else
            jcomRoomType.setEnabled(false);
    }//GEN-LAST:event_jcbRoomTypeActionPerformed

    private void jcbOccupancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOccupancyActionPerformed
        // TODO add your handling code here:
        if(jcbOccupancy.isSelected()){
            jcomCapacity.setEnabled(true);
            
        }else
            jcomCapacity.setEnabled(false);
    }//GEN-LAST:event_jcbOccupancyActionPerformed

    private void jcbPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPriceActionPerformed
        // TODO add your handling code here:
        if(jcbPrice.isSelected()){
            jcomPriceOperator.setEnabled(true);
            jcomPrice.setEnabled(true);
            
        }else{
            jcomPriceOperator.setEnabled(false);
            jcomPrice.setEnabled(false);
        }
    }//GEN-LAST:event_jcbPriceActionPerformed

    private void jfBookingSearchFrameformWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jfBookingSearchFrameformWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfBookingSearchFrameformWindowClosed

    private void jfBookingSearchFrameformWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jfBookingSearchFrameformWindowClosing
        // TODO add your handling code here:
        System.out.println("Closing The Application");
        returnMainFrame();
    }//GEN-LAST:event_jfBookingSearchFrameformWindowClosing

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        // TODO add your handling code here:
        System.out.println("Closing Booking Frame");
        returnMainFrame();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jcomRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomRoomTypeActionPerformed
        // TODO add your handling code here:
        try {
            String selItem = jcomRoomType.getSelectedItem().toString();
            DefaultTableModel srt = bookingDao.search("filterRoomType", selItem);
            showSearchResult(srt);
        } catch (Exception ex) {
            jlMessage.setText("No Available Room");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jcomRoomTypeActionPerformed

    private void jcomCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomCapacityActionPerformed
        // TODO add your handling code here:
        try {
            String selItem = jcomCapacity.getSelectedItem().toString();
            DefaultTableModel srt = bookingDao.search("filterOccupancy", selItem);
            showSearchResult(srt);
        } catch (Exception ex) {
            jlMessage.setText("No Available Room");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jcomCapacityActionPerformed

    private void jcomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomPriceActionPerformed
        // TODO add your handling code here:
        String selOper = jcomPriceOperator.getSelectedItem().toString();
        switch (selOper) {
            case "Less than":
                selOper="<";
                break;
            case "Greater than":
                selOper=">";
                break;
            default:
                selOper="=";
                break;
        }
        String selPrice = jcomPrice.getSelectedItem().toString();
        try {
            DefaultTableModel srt = bookingDao.search("filterPrice", selOper, selPrice);
            showSearchResult(srt);
        } catch (Exception ex) {
            jlMessage.setText("No Available Room");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jcomPriceActionPerformed

    private void jcomPriceOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomPriceOperatorActionPerformed
        // TODO add your handling code here:
        jcomPriceActionPerformed(null);
    }//GEN-LAST:event_jcomPriceOperatorActionPerformed

    private void jbtnBookRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBookRoomActionPerformed
        initJFrame(jfBookingSearchFrame, true, true);
        
    }//GEN-LAST:event_jbtnBookRoomActionPerformed

    private void jbtnCreate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreate5ActionPerformed
        // TODO add your handling code here:
        initJFrame(jfBookingSearchFrame, true, true);
        
        enableUpdateBooking(true);
        jlModeMessage.setText("Update Booking Mode");
    }//GEN-LAST:event_jbtnCreate5ActionPerformed

    private void jbtnCreate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCreate4ActionPerformed

    private void jbtnCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCreate3ActionPerformed

    private void jtSearch_MainFrameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSearch_MainFrameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jbtnSearchApplyActionPerformed(null);
        }
    }//GEN-LAST:event_jtSearch_MainFrameKeyPressed

    private void jbtnSearchApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchApplyActionPerformed
        // TODO add your handling code here:
        bookingFramePojo = bookingDao.getBookingFramePojo().get(jtSearch_MainFrame.getSelectedRow());
        showUpBookingFrameData(bookingFramePojo); // Show up the personal data to the booking frame
        enableMakeBooking(true);
        returnBookingFrame();
    }//GEN-LAST:event_jbtnSearchApplyActionPerformed

    private void costCalculation(BookingFramePOJO bf){
        Long diffDay = (bf.getCheckOut().getTime() - bf.getCheckIn().getTime()) / (24 * 60 * 60 * 1000); 
        Float cost = diffDay * bf.getRoomPrice();
        bf.setTotAmt(cost);
        bf.setPayStatus("UNPAID"); // PAID, UNPAID
    }
    
    private void jbtnMainApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMainApplyActionPerformed
        // TODO add your handling code here:
        if("Make Booking Mode".equals(jlModeMessage.getText())){
            if(updateBookingFrame(bookingFramePojo))
                costCalculation(bookingFramePojo);
            else{
                jlMainMessage.setText("Can't update the form");
                return;
            }
            if(bookingDao.insert(bookingFramePojo)!=-1)
                JOptionPane.showMessageDialog(null, "Making a Booking successfully!", "Notification", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Making a Booking failed!", "Notification", JOptionPane.ERROR_MESSAGE);
        } else if("Update Booking Mode".equals(jlModeMessage.getText())){
            if(updateBookingFrame(bookingFramePojo))
                costCalculation(bookingFramePojo);
            else{
                jlMainMessage.setText("Can't update the form");
                return;
            }
            bookingDao.update(bookingFramePojo);
            JOptionPane.showMessageDialog(null, "Updated Successfully!", "Notification", JOptionPane.INFORMATION_MESSAGE);
        }else{
            jlModeMessage.setText("No Mode Identified");
        }
    }//GEN-LAST:event_jbtnMainApplyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        returnMainFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enableUpdateBooking(Boolean flag){
        jlModeMessage.setText("Update Booking Mode");
        jtfCheckIn.setEnabled(flag);
        jtfCheckOut.setEnabled(flag);
        jtfContactPhone.setEnabled(flag);
        jtfContactEmail.setEnabled(flag);
        jtfBookDate.setEnabled(flag);
        jtfGuest1.setEnabled(flag);
        jtfGuest2.setEnabled(flag);
        jtfGuest3.setEnabled(flag);
        jtfGuest4.setEnabled(flag);
        jtfGuest5.setEnabled(flag);
        
    }
    
    private void enableMakeBooking(Boolean flag){
        jlModeMessage.setText("Make Booking Mode");
        jtfCheckIn.setEnabled(flag);
        jtfCheckOut.setEnabled(flag);
        jtfContactPhone.setEnabled(flag);
        jtfContactEmail.setEnabled(flag);
        jtfBookDate.setEnabled(flag);
        jtfGuest1.setEnabled(flag);
        jtfGuest2.setEnabled(flag);
        jtfGuest3.setEnabled(flag);
        jtfGuest4.setEnabled(flag);
        jtfGuest5.setEnabled(flag);
    }
    
    private void showUpBookingFrameData(BookingFramePOJO bf) {
        //  Booking Info filling out
        if(bf.getBookId()!=null)
            jtfBookId.setText(bf.getBookId().toString());
        if(bf.getCheckIn()!=null)
            jtfCheckIn.setText(bf.getCheckIn().toString());
        if(bf.getCheckOut()!=null)
            jtfCheckOut.setText(bf.getCheckOut().toString());
        if(bf.getContactPhone()!=null)
            jtfContactPhone.setText(bf.getContactPhone());
        if(bf.getContactEmail()!=null)
            jtfContactEmail.setText(bf.getContactEmail());
        if(bf.getHotelId()!=null)
            jtfHotel.setText(bf.getHotelId().toString());
        if(bf.getBookDate()!=null)
            jtfBookDate.setText(bf.getBookDate().toString());
        if(bf.getTotAmt()!=null)
            jtfTotalAmount.setText(bf.getTotAmt().toString());
        if(bf.getRoomId()!=null)
            jtfRoomId.setText(bf.getRoomId().toString());
        if(bf.getRoomNo()!=null)
            jtfRoomNumber.setText(bf.getRoomNo());
        if(bf.getRoomType()!=null)
            jtfRoomType.setText(bf.getRoomType());
        if(bf.getGuest1()!=null)
            jtfGuest1.setText(bf.getGuest1().toString());
        if(bf.getGuest2()!=null)
            jtfGuest2.setText(bf.getGuest2().toString());
        if(bf.getGuest3()!=null)
            jtfGuest3.setText(bf.getGuest3().toString());
        if(bf.getGuest4()!=null)
            jtfGuest4.setText(bf.getGuest4().toString());
        if(bf.getGuest5()!=null)
            jtfGuest5.setText(bf.getGuest5().toString());
        if(bf.getPayStatus()!=null)
            jtfPayStatus.setText(bf.getPayStatus());
    }
    
    private Boolean updateBookingFrame(BookingFramePOJO bf) {
        try {
            if(jtfCheckIn.getText()==null || jtfCheckOut.getText()==null){
                jlMainMessage.setText("Fill out check in / out");
                return false;
            }
            bf.setCheckIn(formatter.parse(jtfCheckIn.getText()));
            bf.setCheckOut(formatter.parse(jtfCheckOut.getText()));
            bf.setBookDate(formatter.parse(jtfBookDate.getText()));
        } catch (ParseException ex) {
            jlMainMessage.setText("Please double check the Date format");
            Logger.getLogger(BookingFrame.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        bf.setCustId(Integer.parseInt(jtfCustomerId.getText()));
        bf.setContactPhone(jtfContactPhone.getText());
        bf.setContactEmail(jtfContactEmail.getText());
        if(!"".equals(jtfGuest1.getText()))
            bf.setGuest1(Integer.parseInt(jtfGuest1.getText()));
        if(!"".equals(jtfGuest2.getText()))
            bf.setGuest2(Integer.parseInt(jtfGuest2.getText()));
        if(!"".equals(jtfGuest3.getText()))
            bf.setGuest3(Integer.parseInt(jtfGuest3.getText()));
        if(!"".equals(jtfGuest4.getText()))
            bf.setGuest4(Integer.parseInt(jtfGuest4.getText()));
        if(!"".equals(jtfGuest5.getText()))
            bf.setGuest5(Integer.parseInt(jtfGuest5.getText()));
        return true;
    }
    
    private void queryCustomer2JTable(){
        DefaultTableModel dtm = this.customerDao.searchCustomer(jtfKeyWord.getText()); // both name or id

        jtResult.setModel(dtm);
        jScrollPane.setViewportView(jtResult);
        jtResult.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane_MainFrame;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnBookRoom;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnCancelSearch;
    private javax.swing.JButton jbtnCreate3;
    private javax.swing.JButton jbtnCreate4;
    private javax.swing.JButton jbtnCreate5;
    private javax.swing.JButton jbtnMainApply;
    private javax.swing.JButton jbtnOkay;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSearchApply;
    private javax.swing.JCheckBox jcbAvailable1;
    private javax.swing.JCheckBox jcbByDate;
    private javax.swing.JCheckBox jcbOccupancy;
    private javax.swing.JCheckBox jcbPrice;
    private javax.swing.JCheckBox jcbRoomType;
    private javax.swing.JComboBox<String> jcomCapacity;
    private javax.swing.JComboBox<String> jcomPrice;
    private javax.swing.JComboBox<String> jcomPriceOperator;
    private javax.swing.JComboBox<String> jcomRoomType;
    private javax.swing.JFrame jfBookingFrame;
    private javax.swing.JFrame jfBookingSearchFrame;
    private javax.swing.JFrame jfSearchResult;
    private javax.swing.JLabel jlMainMessage;
    private javax.swing.JLabel jlMessage;
    private javax.swing.JLabel jlModeMessage;
    private javax.swing.JTable jtResult;
    private javax.swing.JTable jtSearch_MainFrame;
    private javax.swing.JTextField jtfBookDate;
    private javax.swing.JTextField jtfBookId;
    private javax.swing.JTextField jtfCheckIn;
    private javax.swing.JTextField jtfCheckOut;
    private javax.swing.JTextField jtfContactEmail;
    private javax.swing.JTextField jtfContactPhone;
    private javax.swing.JTextField jtfCustomerId;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFirstName;
    private javax.swing.JTextField jtfFrom;
    private javax.swing.JTextField jtfGuest1;
    private javax.swing.JTextField jtfGuest2;
    private javax.swing.JTextField jtfGuest3;
    private javax.swing.JTextField jtfGuest4;
    private javax.swing.JTextField jtfGuest5;
    private javax.swing.JTextField jtfHotel;
    private javax.swing.JTextField jtfKeyWord;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JTextField jtfPayStatus;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTextField jtfRoomId;
    private javax.swing.JTextField jtfRoomNumber;
    private javax.swing.JTextField jtfRoomType;
    private javax.swing.JTextField jtfTo;
    private javax.swing.JTextField jtfTotalAmount;
    // End of variables declaration//GEN-END:variables

    private void showUpPersonData(CustomerFramePOJO bf) {
        jtfCustomerId.setText(bf.getCustId().toString());
        jtfFirstName.setText(bf.getPerFName());
        jtfLastName.setText(bf.getPerLName());
        jtfPhone.setText(bf.getPerPhone().toString());
        jtfEmail.setText(bf.getPerEmail());
    }
}
