/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5148.teamd.gui;

/**
 *
 * @author Vinh Phan
 */
public class GuestFrame extends javax.swing.JFrame {

    /**
     * Creates new form GuestFrame
     */
    public GuestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBy = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jrId = new javax.swing.JRadioButton();
        javax.swing.JRadioButton jrName = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtfSearchKey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jbCancel = new javax.swing.JButton();
        jbApply = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfGuestId = new javax.swing.JTextField();
        jtfPreferences = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfCheckIn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfHotel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfPersonId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfTitle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfTitle1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfTitle2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfDob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfCountry = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfCity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfStreet = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfPostcode = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfCountry4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("GUESTS  PANEL");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jrId.setText("By ID");

        jrName.setSelected(true);
        jrName.setText("By Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Search:");

        jtfSearchKey.setText("Please type it up....");

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jButton1.setText("Search");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSearchKey)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrId)
                            .addComponent(jrName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Messeage");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 245, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jCheckBox1.setText("Do you want to update / insert Guest's profile?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, 380, 36));

        jbCancel.setText("Cancel");
        jPanel7.add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 212, -1, -1));

        jbApply.setText("Apply");
        jbApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApplyActionPerformed(evt);
            }
        });
        jPanel7.add(jbApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 212, 69, -1));

        jLabel4.setText("Guest ID");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 42, -1, -1));

        jtfGuestId.setText("guest ID");
        jtfGuestId.setEnabled(false);
        jPanel7.add(jtfGuestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 39, 98, -1));

        jtfPreferences.setText("preferences");
        jtfPreferences.setEnabled(false);
        jPanel7.add(jtfPreferences, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 70, 99, -1));

        jLabel5.setText("Preferences");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jtfCheckIn.setText("check In");
        jtfCheckIn.setEnabled(false);
        jPanel7.add(jtfCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 101, 99, -1));

        jLabel6.setText("Checked In");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 104, -1, -1));

        jtfHotel.setText("hotel Id");
        jtfHotel.setEnabled(false);
        jPanel7.add(jtfHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 132, 99, -1));

        jLabel7.setText("Hotel ID");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 135, -1, -1));

        jtfPersonId.setText("Person Id");
        jtfPersonId.setEnabled(false);
        jPanel7.add(jtfPersonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 11, 99, -1));

        jLabel8.setText("Person ID");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 14, -1, -1));

        jtfTitle.setText("title");
        jtfTitle.setEnabled(false);
        jPanel7.add(jtfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 39, 99, -1));

        jLabel9.setText("Title");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 42, -1, -1));

        jtfTitle1.setText("first name");
        jtfTitle1.setToolTipText("");
        jtfTitle1.setEnabled(false);
        jPanel7.add(jtfTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 70, 99, -1));

        jLabel10.setText("First Name");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 73, -1, -1));

        jtfTitle2.setText("last name");
        jtfTitle2.setEnabled(false);
        jPanel7.add(jtfTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 101, 99, -1));

        jLabel11.setText("Last name");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 104, -1, -1));

        jtfDob.setText("dob");
        jtfDob.setEnabled(false);
        jPanel7.add(jtfDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 132, 99, -1));

        jLabel12.setText("DOB");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 135, -1, -1));

        jtfCountry.setText("country");
        jtfCountry.setEnabled(false);
        jPanel7.add(jtfCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 166, 99, -1));

        jLabel13.setText("Country");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 169, -1, -1));

        jtfCity.setText("country");
        jtfCity.setEnabled(false);
        jPanel7.add(jtfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 11, 99, -1));

        jLabel14.setText("City");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 14, -1, -1));

        jtfStreet.setText("country");
        jtfStreet.setEnabled(false);
        jPanel7.add(jtfStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 39, 99, -1));

        jLabel15.setText("Street");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 42, -1, -1));

        jtfPostcode.setText("country");
        jtfPostcode.setEnabled(false);
        jPanel7.add(jtfPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 70, 99, -1));

        jLabel16.setText("Postcode");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 73, -1, -1));

        jtfCountry4.setText("country");
        jtfCountry4.setEnabled(false);
        jPanel7.add(jtfCountry4, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 101, 99, -1));

        jLabel17.setText("PH_NO");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 104, -1, -1));

        jtfEmail.setText("country");
        jtfEmail.setEnabled(false);
        jPanel7.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 132, 99, -1));

        jLabel18.setText("Email");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 135, -1, -1));

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbApplyActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        jtfCheckIn.enable(true);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbApply;
    private javax.swing.JButton jbCancel;
    private javax.swing.JRadioButton jrId;
    private javax.swing.JTextField jtfCheckIn;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JTextField jtfCountry;
    private javax.swing.JTextField jtfCountry4;
    private javax.swing.JTextField jtfDob;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfGuestId;
    private javax.swing.JTextField jtfHotel;
    private javax.swing.JTextField jtfPersonId;
    private javax.swing.JTextField jtfPostcode;
    private javax.swing.JTextField jtfPreferences;
    private javax.swing.JTextField jtfSearchKey;
    private javax.swing.JTextField jtfStreet;
    private javax.swing.JTextField jtfTitle;
    private javax.swing.JTextField jtfTitle1;
    private javax.swing.JTextField jtfTitle2;
    private javax.swing.ButtonGroup searchBy;
    // End of variables declaration//GEN-END:variables
}
